In [79]:
# Step 1: uploading and data manipulation
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import keras
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense,Activation,Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.metrics import accuracy_score


In [80]:
data=pd.read_csv("/content/ADHD Data Set (1).csv")
data.head(2)

mean_FZ  median_FZ  mode_FZ     mean_CZ  median_CZ  mode_CZ     mean_PZ  \
0  146.172399        156      191  146.371924        156      156  151.967072   
1  146.459059        121      121  145.589454        121      121  153.285787   

   median_PZ  mode_PZ     mean_C3  ...     mean_T6  media_T6n  mode_T6  \
0        163      200  145.521323  ...  145.275028        156      156   
1        163      126  146.694511  ...  148.303098        156      121   

      mean_O1  median_O1  mode_O1     mean_O2  median_O2  mode_O2  ADHD  
0  145.363255        156      121  144.913031        156      121     0  
1  148.696902        156      121  149.177656        156      121     0  

[2 rows x 58 columns]

In [81]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 58 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   mean_FZ     121 non-null    float64
 1   median_FZ   121 non-null    int64  
 2   mode_FZ     121 non-null    int64  
 3   mean_CZ     121 non-null    float64
 4   median_CZ   121 non-null    int64  
 5   mode_CZ     121 non-null    int64  
 6   mean_PZ     121 non-null    float64
 7   median_PZ   121 non-null    int64  
 8   mode_PZ     121 non-null    int64  
 9   mean_C3     121 non-null    float64
 10  median_C3   121 non-null    int64  
 11  mode_C3     121 non-null    int64  
 12  mean_T3     121 non-null    float64
 13  median_T3   121 non-null    float64
 14  mode_T3     121 non-null    int64  
 15  mean_C4     121 non-null    float64
 16  median_C4   121 non-null    int64  
 17  mode_C4     121 non-null    int64  
 18  mean_T4     121 non-null    float64
 19  median_T4   121 non-null    f

In [82]:
# filling numeric data inn age and fare columns
#mean_age=data.age.mean()
#mean_fare=data.fare.mean()
#print(mean_age,mean_fare)
#data.age.fillna(mean_age,inplace=True)
#data.fare.fillna(mean_fare,inplace=True)

In [83]:
#data.info()

In [84]:
# encoding for categorical data
#data1=pd.get_dummies(data)
#data1.head()

In [85]:
# Step 2: input and output/ split data
X=data.drop(["ADHD"],axis=1)
Y=data.ADHD
print(X.head())
print(Y.head())


      mean_FZ  median_FZ  mode_FZ     mean_CZ  median_CZ  mode_CZ     mean_PZ  \
0  146.172399        156      191  146.371924        156      156  151.967072   
1  146.459059        121      121  145.589454        121      121  153.285787   
2  146.459059        121      121  145.589454        121      121  153.285787   
3  140.233053        121      121  140.678558        121      121  146.490151   
4  136.522379        121      121  136.465369        121      121  142.764696   

   median_PZ  mode_PZ     mean_C3  ...  mode_T5     mean_T6  media_T6n  \
0        163      200  145.521323  ...      163  145.275028        156   
1        163      126  146.694511  ...      126  148.303098        156   
2        163      126  146.694511  ...      126  148.303098        156   
3        126      126  140.451910  ...      163  140.546726        121   
4        126      126  136.499526  ...      126  135.587558        121   

   mode_T6     mean_O1  median_O1  mode_O1     mean_O2  median_O2  m

In [93]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=12)

In [98]:
# Modeling by Logistic
from sklearn.linear_model import LogisticRegression
eqn=LogisticRegression()
eqn.fit(X_train,Y_train)
Ytrain_pred_log=eqn.predict(X_train)
Ytest_pred_log=eqn.predict(X_test)
print(Ytrain_pred_log)
print(Ytest_pred_log)
from sklearn.metrics import accuracy_score
print("training accuracy:", accuracy_score(Y_train,Ytrain_pred_log))
print("Testing accuracy:",accuracy_score(Y_test,Ytest_pred_log))
print(X_train)
print(Y_train)

[1 0 0 1 0 0 0 1 0 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 1 1 1 0 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1
 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1]
[0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0]
training accuracy: 0.8888888888888888
Testing accuracy: 0.5806451612903226
        mean_FZ  median_FZ  mode_FZ     mean_CZ  median_CZ  mode_CZ  \
78   139.865804        121     -125  140.130118        121       15   
101  136.502595        156      156  137.565061        156      121   
23   141.545191        156      156  141.762399        156      156   
115  128.652430        121      543  128.384143        121      -90   
16   139.674276        121      121  140.351535        156      156   
..          ...        ...      ...         ...        ...      ...   
2    146.459059        121      121  145.589454        121      121   
113  125.158806        121     -125  124.844701        121      -19   
6    138.388227        121      156  1

In [95]:
# Decision tree classifier without gridsearchCV
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train,Y_train)
ytest_pred_dt=dtc.predict(X_test)
ytrain_pred_dt=dtc.predict(X_train)
print(ytest_pred_dt)
print(ytrain_pred_dt)
print("Train Accuracy:",accuracy_score(Y_train,ytrain_pred_dt))
print("Test Accuracy:",accuracy_score(Y_test,ytest_pred_dt))

[0 1 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 1 1 1]
[1 1 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0
 0 1 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 0 1 1
 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1]
Train Accuracy: 1.0
Test Accuracy: 0.7741935483870968


In [96]:
# Decision tree classifier with gridsearchCV
from sklearn.tree import DecisionTreeClassifier
dtc_gs = DecisionTreeClassifier()
param_dist_dtc={"criterion":["gini","entropy"],"max_depth":[1,2,3,4,5,6,7,8]}
from sklearn.model_selection import GridSearchCV
grid_dtc=GridSearchCV(dtc,param_grid=param_dist_dtc,cv=10,n_jobs=-1)
grid_dtc.fit(X_train,Y_train)
grid_dtc.best_params_
ytest_pred_dtcGS=grid_dtc.predict(X_test)
ytrain_pred_dtcGS=grid_dtc.predict(X_train)
print(ytest_pred_dtcGS)
print(ytrain_pred_dtcGS)
print("Train Accuracy:",accuracy_score(Y_train,ytrain_pred_dtcGS))
print("Test Accuracy:",accuracy_score(Y_test,ytest_pred_dtcGS))


[0 1 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 1 1 1]
[1 0 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0
 0 1 0 1 0 0 1 1 0 0 0 1 0 1 0 0 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 0 1 1
 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1]
Train Accuracy: 0.9666666666666667
Test Accuracy: 0.7741935483870968


In [90]:
# Random forest classifier witout GridSearchCV
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(X_train,Y_train)
Ytrain_pred_rfc=rfc.predict(X_train)
Ytest_pred_rfc=rfc.predict(X_test)
print(Ytrain_pred_rfc)
print(Ytest_pred_rfc)
print("Train Accuracy:", accuracy_score(Y_train,Ytrain_pred_rfc))
print("Test Accuracy:",accuracy_score(Y_test,Ytest_pred_rfc))

[0 0 1 0 1 1 1 0 0 1 0 1 1 1 0 0 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1 0 1 0 0 0 1
 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1 1 1 1]
[1 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0 1 1 0 1 1 0]
Train Accuracy: 1.0
Test Accuracy: 0.76


In [99]:
# RandomForestClassifier with GridSearchCV
from sklearn.ensemble import RandomForestClassifier
rfc_gs=RandomForestClassifier()
param_dist_rfc={"max_depth":[3,5,6],"n_estimators":[100,150,200,250],"criterion":["gini","entropy"]}# tuning parameters
print("Tuning Parameters:", param_dist_rfc)
from sklearn.model_selection import GridSearchCV
grid_rfc=GridSearchCV(rfc_gs,param_dist_rfc,cv=5,n_jobs=-1)
grid_rfc.fit(X_train,Y_train)
Ytrain_pred_rfc_gs=rfc.predict(X_train)
Ytest_pred_rfc_gs=rfc.predict(X_test)
print("training accuracy:",accuracy_score(Y_train,Ytrain_pred_rfc_gs))
print("testing accuracy:",accuracy_score(Y_test,Ytest_pred_rfc_gs))

Tuning Parameters: {'max_depth': [3, 5, 6], 'n_estimators': [100, 150, 200, 250], 'criterion': ['gini', 'entropy']}
training accuracy: 0.9444444444444444
testing accuracy: 0.967741935483871


In [100]:
grid_rfc.best_params_

{'criterion': 'entropy', 'max_depth': 6, 'n_estimators': 100}